import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { useState } from "react";
import { Check, Copy, Play, TerminalSquare } from "lucide-react";
import { AppStudioModal } from "@/components/apps/AppStudioModal";
import type { AppManifest } from "@/lib/apps.types";

function CodeBlock({ language, value }: { language: string; value: string }) {
  const [copied, setCopied] = useState(false);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);

  const cleanLang = language?.toLowerCase().trim() || "";
  // All languages can now be previewed, compiled, or executed inside our Universal Compiler Sandbox!
  const canPreview = Boolean(value && value.trim().length > 0);

  const getPreviewApp = (): AppManifest => {
    let template: any = "universal-code";
    let path = "main.code";
    const cl = cleanLang;

    if (cl === "html" || value.trim().startsWith("<!DOCTYPE") || value.trim().startsWith("<html")) {
      template = "html-js";
      path = "index.html";
    } else if (cl === "tsx" || cl === "jsx" || cl === "react" || value.includes("export default") || value.includes("React.FC")) {
      template = "react";
      path = "App.tsx";
    } else if (cl === "py" || cl === "python") {
      template = "python";
      path = "main.py";
    } else if (cl === "rs" || cl === "rust") {
      template = "rust";
      path = "main.rs";
    } else if (cl === "go" || cl === "golang") {
      template = "go";
      path = "main.go";
    } else if (cl === "c" || cl === "cpp" || cl === "c++") {
      template = cl === "c" ? "c" : "cpp";
      path = cl === "c" ? "main.c" : "main.cpp";
    } else if (cl === "java") {
      template = "java";
      path = "Main.java";
    } else if (cl === "cs" || cl === "csharp" || cl === "c#") {
      template = "csharp";
      path = "Program.cs";
    } else if (cl === "rb" || cl === "ruby") {
      template = "ruby";
      path = "main.rb";
    } else if (cl === "php") {
      template = "php";
      path = "index.php";
    } else if (cl === "sql" || cl === "sqlite") {
      template = "sql";
      path = "query.sql";
    } else if (cl === "sh" || cl === "bash" || cl === "shell" || cl === "zsh") {
      template = "bash";
      path = "script.sh";
    } else if (cl === "swift") {
      template = "swift";
      path = "main.swift";
    } else if (cl === "kt" || cl === "kotlin") {
      template = "kotlin";
      path = "Main.kt";
    } else if (cl === "r") {
      template = "r";
      path = "script.R";
    } else if (cl === "js" || cl === "javascript" || cl === "ts" || cl === "typescript") {
      template = "node";
      path = cl.includes("ts") ? "index.ts" : "index.js";
    }

    return {
      appId: `snippet-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      title: `${cleanLang ? cleanLang.toUpperCase() : "Universal Code"} Preview & Compiler`,
      description: `Live compilation, execution, & preview for ${cleanLang || "source code"} generated by NOVA AI`,
      template,
      files: [{ path, language: cleanLang || "text", content: value }],
      entryPoint: path,
    };
  };

  return (
    <div className="my-3 rounded-xl overflow-hidden border border-zinc-800 bg-[#1e1e2e] shadow-sm">
      <div className="flex items-center justify-between px-3 py-1.5 text-xs text-zinc-400 bg-black/40 border-b border-white/5">
        <div className="flex items-center gap-2">
          <TerminalSquare className="size-3.5 text-primary" />
          <span className="font-mono font-bold text-zinc-300">{language || "universal-code"}</span>
        </div>
        <div className="flex items-center gap-2">
          {canPreview && (
            <button
              type="button"
              onClick={() => setIsPreviewOpen(true)}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-primary/20 text-primary hover:bg-primary/30 transition text-[11px] font-bold tracking-wide"
            >
              <Play className="size-3 text-emerald-400 fill-emerald-400" />
              <span>Compile & Preview</span>
            </button>
          )}
          <button
            onClick={() => {
              navigator.clipboard.writeText(value);
              setCopied(true);
              setTimeout(() => setCopied(false), 1500);
            }}
            className="flex items-center gap-1 hover:text-white transition px-2 py-0.5 rounded border border-transparent hover:border-zinc-700"
          >
            {copied ? <Check className="size-3 text-emerald-400" /> : <Copy className="size-3" />}
            {copied ? "Copied" : "Copy"}
          </button>
        </div>
      </div>
      <SyntaxHighlighter
        language={language || "text"}
        style={oneDark}
        customStyle={{ margin: 0, padding: "1.1rem", background: "transparent", fontSize: "0.85rem", lineHeight: "1.5" }}
        wrapLongLines
      >
        {value.replace(/\n$/, "")}
      </SyntaxHighlighter>

      {canPreview && (
        <AppStudioModal
          app={getPreviewApp()}
          isOpen={isPreviewOpen}
          onClose={() => setIsPreviewOpen(false)}
        />
      )}
    </div>
  );
}

export function Markdown({ content }: { content: string }) {
  return (
    <div className="prose-chat">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          code({
            inline,
            className,
            children,
            ...props
          }: {
            inline?: boolean;
            className?: string;
            children?: React.ReactNode;
          }) {
            const match = /language-(\w+)/.exec(className || "");
            const value = String(children ?? "");
            if (!inline && (match || value.includes("\n"))) {
              return <CodeBlock language={match?.[1] ?? ""} value={value} />;
            }
            return (
              <code className={className} {...props}>
                {children}
              </code>
            );
          },
          a({ children, href }) {
            return (
              <a href={href} target="_blank" rel="noreferrer noopener">
                {children}
              </a>
            );
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
